### ISSUE TITLE
Ajouter un composant : loader

### ISSUE THREAD

**Issue by ameliedefrance** [Elao/elao-admin#32]
Plusieurs variantes pour plusieurs usages ?
- [ ] tournicoti tournicoton
- [ ] trois petits points
- [ ] autre ?

**Comment by ogizanagi** [comment]
Est-ce qu'on prévoit des loaders:

- de blocs (ex chargement d'un bloc complet (avec overlay ?), par exemple lors de la soumission d'un formulaire ou chargement de données) (encore faut-il avoir une notion de blocs suffisamment avancée dans l'admin)
- d'input (type `<select>` lors du chargement des données)
- de page (overlay, loader au centre de la page, texte potentiel)

? (sujet vaste)

**Comment by ameliedefrance** [comment]
Ça dépend un peu du besoin : 

- pour le loader de bloc je pense que l'idéal c'est de prévoir un état spécifiquement pour les composants concernés (au pif : un tableau qui charge on aurait un style `table` et un `table--loading` / pour un formulaire en cours de soumission on peut imaginer pareil un état du formulaire qui devient disabled et un animation sur le bouton)
- qu'est ce que tu entends par "d'input (type `<select>` lors du chargement des données)" ?
- de page j'avais pas poussé si loin je pensais juste à une petite div avec une animation qui tourne à l'infini qu'on affiche/cache mais carrément 👍

**Comment by ogizanagi** [comment]
> qu'est ce que tu entends par "d'input (type <select> lors du chargement des données)" ?

Par exemple sur M&M, on a un champs `<seclect>` simple, mais qui peut mettre un peu de temps avant d'être disponible, en attendant de récupérer les données:

![Jun-04-2021 09-06-49](https://user-images.githubusercontent.com/2211145/120760455-6c2f7780-c514-11eb-9df4-d5d0c7c31438.gif)

Ici on remplace complètement le champ par le loader, mais selon l'app, le besoin et le rendu souhaité, on peut avoir ce champ disabled avec une indication qu'il est en cours de chargement. Mais ça peut être par exemple prévoir simplement de rendre un icon (dont un spinner) à droite du champ.
