### ISSUE TITLE
Intégrer choice.js

### ISSUE THREAD

**Issue by Tom32i** [Elao/elao-admin#37]
[choice.js](https://github.com/Choices-js/Choices) est un outil JS qui ajoute une couche "recherche" au select.

Ça fait un petit autocomplete, et ça permet aussi d'afficher les select multiple joliement sous forme de liste de tags.
Il est vanilla (et donc sans jquery), 100% customisable sur les classes et le style, et assez efficace. 

On l'utilise notamment sur tribu : 

| ![Capture d’écran 2021-06-09 à 08 40 13](https://user-images.githubusercontent.com/1846873/121305826-59df8000-c8fe-11eb-893a-b8116928641c.png) | ![Capture d’écran 2021-06-09 à 08 41 05](https://user-images.githubusercontent.com/1846873/121305930-7ed3f300-c8fe-11eb-81b9-a96a70208691.png) |
| -- | -- |

**Comment by ameliedefrance** [comment]
Carrément, on peut tester 👍

**Comment by ogizanagi** [comment]
Autre alternative vanilla qui semble gagner en popularité et être très complète: https://tom-select.js.org/
