### ISSUE TITLE
[Design System Elao] passer la démo en PHP 8

### ISSUE THREAD

**Issue by xavier-rdo** [Elao/elao-admin#63]
- Mettre à jour les fichiers `.phpversion` dans [`elao-admin`](https://github.com/Elao/elao-admin) **ET** la démo (app Symfony)
- Mettre à jour la démo de `elao-admin` en Symfony 5.4
- Mettre à jour la version de PHP dans la CI/GHA de `elao-admin`
- Mettre à jour les dépendances `node/npm` dans le dossier `demo` de `elao-admin`
- Retirer Php 7.4 du bundle [`ElaoAdminThemeBundle`](https://github.com/Elao/ElaoAdminThemeBundle)

**Comment by ogizanagi** [comment]
Closed by #62
